---
title: "Reading data from the web"
data: "10/10/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
```

# extracting data from the web; 
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = 
  read_html(url)
```
# don't want all the tables from the website
```{r}
(drug_use_xml %>%  html_nodes(css="table")) %>% 
  .[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```
* a "." acts as a place holder
 * slice() gets ride of a row. here slice(-1) gets rid of the first row.
 
## get harry potter data
```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")
```

```{r}
hpsaga_html %>% 
  html_nodes(".lister-item-header a") %>% 
  html_text()

hp_movie_runtime=
  hpsaga_html %>% 
  html_nodes(".runtime") %>% 
  html_text()
  

hp_df=
  tibble(
    title=hp_movie_names,
    titleruntime = hp_movie_runtime,
    money = hp_movie_money
  )
```

# USe API
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

* Json is more of a flexible way of extracting data

